import os
import json
from PIL import Image, ImageDraw, ImageFont

def process_target(image_path, response_data, output_dir="media/output/pipeline_sim", grid_size=10.0):
    """
    Parses the JSON response data, plots the crosshair target over the original image,
    saves the image, and logs the result.
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Handle string vs dictionary
    import ast
    try:
        data = json.loads(response_data) if isinstance(response_data, str) else response_data
    except Exception as e:
        try:
            # Fallback for Python dictionary strings generated by model (e.g. True instead of true)
            if isinstance(response_data, str):
                clean_data = response_data.replace("null", "None").replace("true", "True").replace("false", "False")
                data = ast.literal_eval(clean_data)
        except Exception as e2:
            print(f"⚠️ parsing error: {e2}")
            print(f"Raw response was: {response_data}")
            return None
        
    image = Image.open(image_path).convert("RGB")
    draw = ImageDraw.Draw(image)
    w, h = image.size

    try:
        font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 22)
    except:
        font = ImageFont.load_default()

    if data.get("target_spotted", False):
        name = data.get("target_name", "Target")
        distance = data.get("distance_meters", 0)
        grid_pos = data.get("grid_position", "")

        # Parse coordinates (handling decimals)
        try:
            gx, gy = map(float, grid_pos.split(','))
            cx = int((gx / grid_size) * w)
            cy = int((gy / grid_size) * h)
        except Exception as e:
            print(f"⚠️ Coordinate parsing error: {e}")
            cx, cy = w // 2, h // 2

        # --- 1. DRAW CROSSHAIR ---
        draw.ellipse([cx-25, cy-25, cx+25, cy+25], outline="#00ff00", width=3)
        draw.ellipse([cx-3, cy-3, cx+3, cy+3], fill="red")
        draw.line([cx, cy-25, cx, cy-8], fill="#00ff00", width=3) # Top
        draw.line([cx, cy+8, cx, cy+25], fill="#00ff00", width=3) # Bottom
        draw.line([cx-25, cy, cx-8, cy], fill="#00ff00", width=3) # Left
        draw.line([cx+8, cy, cx+25, cy], fill="#00ff00", width=3) # Right

        # --- 2. DRAW LABEL ---
        label = f"{name} • {distance}m"
        text_bbox = draw.textbbox((0, 0), label, font=font)
        text_w = text_bbox[2] - text_bbox[0]
        
        draw.rectangle([cx - (text_w//2) - 5, cy + 30, cx + (text_w//2) + 5, cy + 60], fill="#00ff00")
        draw.text((cx - (text_w//2), cy + 32), label, fill="black", font=font)

        # --- 3. SAVE IMAGE FIRST ---
        out_name = "target_" + os.path.basename(image_path)
        out_path = os.path.join(output_dir, out_name)
        image.save(out_path)
        
        # --- 4. PRINT TERMINAL OUTPUT ---
        direction = data.get("direction", "ahead")
        next_action = data.get("next_action", "")
        
        print("\n" + "="*50)
        print(f"✅ TARGET MARKED AND SAVED: {out_path}")
        print(f"📍 Grid Coordinate: {grid_pos} --> Image Pixel: ({cx}, {cy})")
        print("-" * 50)
        print("🤖 ASSISTANT SAYS:")
        print(f'   "Found {name}, {direction}, about {distance} meters."')
        if next_action:
            print(f'   "{next_action}"')
        print("="*50 + "\n")

    else:
        print("\n❌ Target not spotted. Assistant says: \"No target found.\"")
        
        # Save unmodified image if nothing is found
        out_name = "target_not_found_" + os.path.basename(image_path)
        out_path = os.path.join(output_dir, out_name)
        image.save(out_path)

    return out_path
